package X;

import android.net.Uri;
import android.os.Bundle;
import com.whatsapp.jid.UserJid;
import java.io.File;
import java.util.ArrayList;

/* renamed from: X.3BR  reason: invalid class name */
public class AnonymousClass3BR {
    public final int A00;
    public final int A01;
    public final int A02;
    public final Uri A03;
    public final Bundle A04;
    public final C207269up A05;
    public final AnonymousClass3PE A06;
    public final AnonymousClass141 A07;
    public final AnonymousClass11F A08;
    public final AnonymousClass147 A09;
    public final UserJid A0A;
    public final File A0B;
    public final Long A0C;
    public final Long A0D;
    public final String A0E;
    public final String A0F;
    public final String A0G;
    public final String A0H;
    public final String A0I;
    public final String A0J;
    public final String A0K;
    public final String A0L;
    public final String A0M;
    public final String A0N;
    public final String A0O;
    public final String A0P;
    public final ArrayList A0Q;
    public final ArrayList A0R;
    public final boolean A0S;
    public final boolean A0T;
    public final boolean A0U;
    public final boolean A0V;
    public final boolean A0W;
    public final boolean A0X;
    public final boolean A0Y;
    public final boolean A0Z;
    public final boolean A0a;
    public final boolean A0b;

    public AnonymousClass3BR(AnonymousClass3BS r2) {
        this.A02 = r2.A02;
        this.A08 = r2.A08;
        this.A07 = r2.A07;
        this.A0V = r2.A0V;
        this.A0a = r2.A0a;
        this.A0U = r2.A0U;
        this.A0b = r2.A0b;
        this.A0W = r2.A0W;
        this.A0Z = r2.A0Z;
        this.A0Y = r2.A0Y;
        this.A0X = r2.A0X;
        this.A0P = r2.A0M;
        this.A01 = r2.A01;
        this.A0D = r2.A0D;
        this.A0T = r2.A0T;
        this.A00 = r2.A00;
        this.A0H = r2.A0H;
        this.A0N = r2.A0O;
        this.A0O = r2.A0P;
        this.A0L = r2.A0L;
        this.A0M = r2.A0N;
        this.A0R = r2.A0R;
        this.A0Q = r2.A0Q;
        this.A03 = r2.A03;
        this.A04 = r2.A04;
        this.A05 = r2.A05;
        this.A0A = r2.A0A;
        this.A0B = r2.A0B;
        this.A09 = r2.A09;
        this.A0J = r2.A0J;
        this.A0I = r2.A0I;
        this.A0E = r2.A0E;
        this.A0G = r2.A0G;
        this.A0F = r2.A0F;
        this.A0C = r2.A0C;
        this.A06 = r2.A06;
        this.A0S = r2.A0S;
        this.A0K = r2.A0K;
    }
}
