package X;

/* renamed from: X.5JH  reason: invalid class name */
public final class AnonymousClass5JH extends C117795mq {
    public static final AnonymousClass5JH A00 = new AnonymousClass5JH();

    public AnonymousClass5JH() {
        super("WA_UNIT_TEST", "DEBUG_TOOL", "XFAM_CROSSPOSTING_NATIVE_AUTH_TOKEN_XCHANGE_GQL", "XFAM_CROSSPOSTING_FB_ACCOUNT_CACHE", "XFAM_CROSSPOSTING_DB_SQL", "XFAM_CROSSPOSTING_ELIGIBILITY_GQL", "XFAM_CROSSPOSTING_NATIVE_AUTH_UI", "XFAM_CROSSPOSTING_REQUEST_GQL", "XFAM_CROSSPOSTING_REQUEST_MANAGER", "XFAM_CROSSPOSTING_WEB_AUTH_PROFILE_DATA_FETCH_GQL", "XFAM_CROSSPOSTING_NATIVE_AUTH_PROFILE_DATA_FETCH_GQL", "XFAM_CROSSPOSTING_STATUS_PRIVACY_UI", "XFAM_CROSSPOSTING_UNLINKING_GRAPH_API");
    }
}
