package X;

/* renamed from: X.2xD  reason: invalid class name */
public abstract class AnonymousClass2xD {
    public static final String A00;
    public static final String A01;
    public static final String A02;
    public static final String A03;
    public static final String A04;
    public static final String A05;
    public static final String A06;
    public static final String A07;
    public static final String A08;
    public static final String A09;
    public static final String A0A;
    public static final String A0B;
    public static final String A0C;
    public static final String A0D;
    public static final String A0E;
    public static final String A0F;
    public static final String A0G;
    public static final String A0H;
    public static final String A0I;
    public static final String A0J;
    public static final String A0K;
    public static final String A0L;
    public static final String A0M;
    public static final String A0N;

    public static void A00(StringBuilder sb) {
        sb.append(8);
        sb.append("', '");
        sb.append(10);
        sb.append("', '");
        sb.append(7);
        sb.append("', '");
    }

    static {
        StringBuilder A0u = AnonymousClass000.A0u();
        A0u.append("SELECT ");
        String str = C56842wy.A01;
        A0u.append(str);
        A0u.append(" FROM ");
        String A1C = C36431kI.A1C("available_message_view", A0u);
        String A0r = C36401kF.A0r("chat_row_id = ?", A0u);
        A0u.append("from_me = 0");
        A0u.append(A0r);
        A0u.append("sort_id <= ?");
        A0u.append(A0r);
        A0u.append("sort_id > ?");
        A0u.append(A0r);
        A0u.append("status NOT IN (16, 10)");
        A0u.append(A0r);
        A0u.append("message_type NOT IN ('8', '10', '15')");
        A0u.append(" ORDER BY sort_id DESC ");
        A0N = AnonymousClass000.A0q("LIMIT 4096", A0u);
        StringBuilder A0u2 = AnonymousClass000.A0u();
        C36321k7.A1O("   SELECT ", str, " FROM ", "available_message_view", A0u2);
        String A0p = AnonymousClass000.A0p(A1C, "chat_row_id = ?", A0u2);
        A0J = A0p;
        StringBuilder A0k = C36331k8.A0k(A0p, A0r);
        A0k.append("message_type = ?");
        A08 = AnonymousClass000.A0q(" ORDER BY sort_id DESC", A0k);
        StringBuilder A0u3 = AnonymousClass000.A0u();
        C36321k7.A1O(A0p, A0r, "message_type", " NOT IN ('", A0u3);
        A00(A0u3);
        A0u3.append(15);
        A0u3.append("', '");
        A0u3.append(19);
        C36321k7.A1O("') AND ", "from_me = 0", " ORDER BY sort_id DESC", " LIMIT ?", A0u3);
        A04 = A0u3.toString();
        StringBuilder A0u4 = AnonymousClass000.A0u();
        C36321k7.A1O(A0p, A0r, "message_type", " NOT IN ('", A0u4);
        A00(A0u4);
        A0u4.append(19);
        C36321k7.A1O("') AND ", "from_me = 0", " ORDER BY sort_id DESC", " LIMIT ?", A0u4);
        A05 = A0u4.toString();
        StringBuilder A0u5 = AnonymousClass000.A0u();
        C36321k7.A1O(A0p, A0r, "message_type", " NOT IN ('", A0u5);
        A00(A0u5);
        A0u5.append(19);
        A0u5.append("') AND ");
        A0u5.append("from_me = 0");
        AnonymousClass000.A1D(" AND (view_mode IS NULL OR view_mode = 0) ", " ORDER BY sort_id DESC", " LIMIT ?", A0u5);
        A06 = A0u5.toString();
        StringBuilder A0u6 = AnonymousClass000.A0u();
        C36321k7.A1O(A0p, A0r, "message_type", " NOT IN ('", A0u6);
        A00(A0u6);
        A0u6.append(15);
        A0u6.append("', '");
        A0u6.append(19);
        A0u6.append("') AND ");
        AnonymousClass000.A1D("from_me = 1", " ORDER BY sort_id DESC", " LIMIT ?", A0u6);
        A07 = A0u6.toString();
        String A0q = AnonymousClass000.A0q("(message_type != '8')", C36331k8.A0k(A0p, A0r));
        StringBuilder A0k2 = C36331k8.A0k(A0q, A0r);
        A0k2.append("_id >= ?");
        A0A = AnonymousClass000.A0q(" ORDER BY _id ASC", A0k2);
        StringBuilder A0v = AnonymousClass000.A0v(A0q);
        A0v.append(" ORDER BY ");
        A09 = AnonymousClass000.A0p("sort_id DESC", " LIMIT ?", A0v);
        StringBuilder A0k3 = C36331k8.A0k("   SELECT ", str);
        A0k3.append(", ");
        C36321k7.A1O("chat_row_id", " FROM ", "available_message_view", A1C, A0k3);
        A0k3.append("_id >= ? ");
        A0k3.append(A0r);
        A0k3.append("_id < ? ");
        A0k3.append(" AND (view_mode IS NULL OR view_mode = 0) ");
        A0k3.append(" AND (expire_timestamp IS NULL OR expire_timestamp >= ? OR keep_in_chat = 1) ");
        A0k3.append(" ORDER BY _id DESC");
        A0L = AnonymousClass000.A0q(" LIMIT ? ", A0k3);
        StringBuilder A0u7 = AnonymousClass000.A0u();
        C36321k7.A1O("   SELECT ", str, " FROM ", "available_message_view", A0u7);
        A0u7.append(" AS message  JOIN (  SELECT ");
        A0u7.append("_id");
        A0u7.append(" AS chat_view_table_id  FROM ");
        A0u7.append("chat_view");
        A0u7.append(A1C);
        A0u7.append("raw_string_jid");
        A0u7.append(" NOT LIKE '%@g.us' AND ");
        A0u7.append("raw_string_jid");
        C36321k7.A1O(" NOT LIKE '%@broadcast' )AS chat ON message.chat_row_id = chat.chat_view_table_id WHERE ", "_id >= ? ", A0r, "_id < ? ", A0u7);
        A0u7.append(" AND (view_mode IS NULL OR view_mode = 0) ");
        AnonymousClass000.A1D(" AND (expire_timestamp IS NULL) ", A0r, "message_type", A0u7);
        A0u7.append(" NOT IN (");
        A0u7.append(42);
        A0u7.append(", ");
        A0u7.append(43);
        A0u7.append(", ");
        A0u7.append(78);
        A0u7.append(", ");
        A0u7.append(82);
        AnonymousClass000.A1D(")", " ORDER BY _id DESC", " LIMIT ? ", A0u7);
        A0K = A0u7.toString();
        StringBuilder A0I2 = C36321k7.A0I("   SELECT ", str, ", ", "chat_row_id", " FROM ");
        A0I2.append("available_message_view");
        A0I2.append(A1C);
        A0I2.append("_id > ? ");
        A0I2.append(A0r);
        C36321k7.A1O("_id <= ? ", " AND (expire_timestamp IS NULL OR expire_timestamp >= ? OR keep_in_chat = 1) ", " ORDER BY _id ASC", " LIMIT ? ", A0I2);
        A0I = A0I2.toString();
        StringBuilder A0I3 = C36321k7.A0I("SELECT ", str, " FROM ", "available_message_view", A1C);
        A0I3.append("chat_row_id = ?");
        A0I3.append(A0r);
        A0I3.append("starred = 1");
        A0I3.append(A0r);
        StringBuilder A0k4 = C36331k8.A0k(AnonymousClass000.A0q("(message_type != '7')", A0I3), " ORDER BY ");
        A0k4.append("sort_id");
        A01 = AnonymousClass000.A0q(" DESC", A0k4);
        StringBuilder A0I4 = C36321k7.A0I("SELECT ", str, " FROM ", "available_message_view", A1C);
        A0I4.append("starred = 1");
        String A0p2 = AnonymousClass000.A0p(A0r, "(message_type != '7')", A0I4);
        StringBuilder A0u8 = AnonymousClass000.A0u();
        C36321k7.A1O(A0p2, " ORDER BY ", "timestamp", " DESC", A0u8);
        A02 = A0u8.toString();
        StringBuilder A0I5 = C36321k7.A0I("SELECT ", str, " FROM ", "available_message_view", A1C);
        A0I5.append("chat_row_id = ?");
        A0I5.append(A0r);
        A00 = C36321k7.A0D(AnonymousClass000.A0q("_id IN (SELECT message_row_id FROM message_ephemeral WHERE keep_in_chat = 1)", A0I5), " ORDER BY sort_id DESC");
        A0B = AnonymousClass000.A0q("_id = ?", C36321k7.A0I("SELECT ", str, " FROM ", "available_message_view", A1C));
        StringBuilder A0I6 = C36321k7.A0I("SELECT ", str, " FROM ", "available_message_view", A1C);
        AnonymousClass000.A1D("chat_row_id = ? AND ", "_id <= ? ", " AND (view_mode IS NULL OR view_mode = 0) ", A0I6);
        A0I6.append(" ORDER BY _id DESC ");
        A0C = AnonymousClass000.A0q("LIMIT 1", A0I6);
        A0E = AnonymousClass000.A0q("sort_id = ?", C36321k7.A0I("SELECT ", str, " FROM ", "available_message_view", A1C));
        StringBuilder A0I7 = C36321k7.A0I("SELECT ", str, " FROM ", "available_message_view", A1C);
        A0I7.append("sort_id = ?");
        A0D = AnonymousClass000.A0p(A0r, "chat_row_id = ?", A0I7);
        StringBuilder A0I8 = C36321k7.A0I("SELECT ", str, " FROM ", "available_message_view", A1C);
        A0I8.append("chat_row_id = ?");
        A0I8.append(" ORDER BY sort_id DESC");
        A0H = AnonymousClass000.A0q(" LIMIT 1", A0I8);
        StringBuilder A0I9 = C36321k7.A0I("SELECT ", str, " FROM ", "available_message_view", A1C);
        A0I9.append("chat_row_id = ?");
        A0I9.append(A0r);
        AnonymousClass000.A1D("message_type NOT IN ('8', '10', '90', '12') ", " ORDER BY sort_id DESC", " LIMIT ?", A0I9);
        A0F = A0I9.toString();
        StringBuilder A0I10 = C36321k7.A0I("SELECT ", str, " FROM ", "available_message_view", A1C);
        A0I10.append("message_type IN ('9' , '26' )");
        A0I10.append(A0r);
        C36321k7.A1O("origin != 7", A0r, "chat_row_id = ?", " ORDER BY sort_id DESC", A0I10);
        A03 = A0I10.toString();
        StringBuilder A0I11 = C36321k7.A0I("SELECT ", str, " FROM ", "available_message_view", A1C);
        A0I11.append("message_type = 12");
        A0G = AnonymousClass000.A0q(" ORDER BY _id", A0I11);
        StringBuilder A0I12 = C36321k7.A0I("SELECT ", str, " FROM ", "available_message_view", A1C);
        A0I12.append("from_me = 1");
        A0I12.append(A0r);
        A0I12.append("status < 4");
        A0I12.append(A0r);
        A0I12.append("_id > ?");
        A0I12.append(A0r);
        A0M = AnonymousClass000.A0p("sort_id > 0", " ORDER BY _id ASC", A0I12);
    }
}
