package X;

/* renamed from: X.2x9  reason: invalid class name */
public abstract class AnonymousClass2x9 {
    public static final String A00;
    public static final String A01;
    public static final String A02;
    public static final String A03;
    public static final String A04;
    public static final String A05;
    public static final String A06;
    public static final String A07;
    public static final String A08;
    @Deprecated
    public static final String A09;
    public static final String A0A;
    @Deprecated
    public static final String A0B;
    @Deprecated
    public static final String A0C;

    static {
        StringBuilder A0u = AnonymousClass000.A0u();
        A0u.append("SELECT ");
        String str = C56842wy.A01;
        A0u.append(str);
        A0u.append(" FROM ");
        String A1C = C36431kI.A1C("message_view", A0u);
        A0u.append("sort_id");
        A0u.append(" IN (SELECT docid FROM ");
        A0u.append("message_ftsv2");
        A0u.append(" AS ");
        A0u.append("message_ftsv2");
        A0u.append(", ");
        A0u.append("available_message_view");
        A0u.append(" AS message  WHERE ");
        A0u.append("message_ftsv2");
        A0u.append(" MATCH ? AND ");
        A0u.append("message_ftsv2.docid = message.sort_id) ");
        A0u.append(" ORDER BY ");
        A0u.append("sort_id");
        A03 = AnonymousClass000.A0q(" DESC", A0u);
        StringBuilder A0u2 = AnonymousClass000.A0u();
        AnonymousClass000.A1D("SELECT ", str, ", ", A0u2);
        A0u2.append("docid");
        A0u2.append(", ");
        A0u2.append("content");
        A0u2.append(", ");
        A0u2.append("fts_jid");
        A0u2.append(" FROM ");
        A0u2.append("message_ftsv2 AS fts");
        A0u2.append(" JOIN ");
        A0u2.append("available_message_view AS message");
        A0u2.append(A1C);
        String A0r = C36401kF.A0r("fts.docid = message.sort_id", A0u2);
        A0u2.append("message_ftsv2");
        A07 = AnonymousClass000.A0q(" MATCH ? ", A0u2);
        StringBuilder A0u3 = AnonymousClass000.A0u();
        C36321k7.A1O("SELECT ", str, ", ", "docid", A0u3);
        A0u3.append(", ");
        C36321k7.A1O("content", ", ", "fts_jid", " FROM ", A0u3);
        AnonymousClass000.A1D("message_ftsv2 AS fts", " JOIN ", "available_message_view AS message", A0u3);
        C36321k7.A1O(" ON ", "fts.docid = message.sort_id", A1C, "message_ftsv2", A0u3);
        A06 = AnonymousClass000.A0q(" MATCH ? ", A0u3);
        StringBuilder A0v = AnonymousClass000.A0v("SELECT ");
        C36361kB.A1R("message", A0v, C56842wy.A03);
        A0v.append(", links.link_index AS link_index FROM ");
        A0v.append("available_message_view AS message");
        A0v.append(" INNER JOIN ");
        A0v.append("message_link AS links");
        A0v.append(" ON message.");
        A0v.append("_id");
        A0v.append(" = links.");
        A0v.append("message_row_id");
        A0v.append(" WHERE message.");
        A0v.append("sort_id");
        A0v.append(" IN ");
        A0v.append("(SELECT docid FROM message_ftsv2 WHERE content MATCH ? )");
        A02 = AnonymousClass000.A0q(" ORDER BY sort_id DESC", A0v);
        StringBuilder A0I = C36321k7.A0I("SELECT ", str, " FROM ", "available_message_view", A1C);
        A0I.append("sort_id");
        A0I.append(" IN ");
        A0A = AnonymousClass000.A0p("(SELECT docid FROM message_ftsv2 AS messages_fts, message_view AS message WHERE messages_fts.content MATCH ? AND messages_fts.docid = message.sort_id AND message.starred = 1 AND (message_type != '7'))", " ORDER BY sort_id DESC", A0I);
        StringBuilder A0I2 = C36321k7.A0I("SELECT ", str, " FROM ", "message_view", A1C);
        A0I2.append("_id");
        A0I2.append(" IN (SELECT docid FROM ");
        A0I2.append("messages_fts");
        A0I2.append(" AS messages_fts, ");
        A0I2.append("available_message_view");
        A0I2.append(" AS message  WHERE content MATCH ? AND messages_fts.docid = message.");
        A0I2.append("_id");
        A0I2.append(" AND message.");
        A0I2.append("message_type");
        A0I2.append(" IN ('");
        A0I2.append(9);
        A0I2.append("' , '");
        A0I2.append(26);
        A0I2.append("' ) AND ");
        C36321k7.A1O("message.chat_row_id = ?) ", " ORDER BY ", "sort_id", " DESC", A0I2);
        A00 = A0I2.toString();
        StringBuilder A0u4 = AnonymousClass000.A0u();
        AnonymousClass000.A1D("SELECT ", str, ", links.link_index AS link_index FROM ", A0u4);
        A0u4.append("message_view AS message");
        A0u4.append(", ");
        A0u4.append("(SELECT message_row_id, link_index FROM message_link AS link WHERE link.chat_row_id=? AND message_row_id IN ( SELECT docid FROM messages_fts, available_message_view AS message WHERE content MATCH ? AND messages_fts.docid = message._id)) links");
        A0u4.append(A1C);
        A0u4.append("message._id = links.message_row_id ");
        A01 = AnonymousClass000.A0q(" ORDER BY _id DESC", A0u4);
        StringBuilder A0k = C36331k8.A0k(str, ", ");
        A0k.append("messages_fts.docid AS docid");
        A0k.append(", ");
        String A0q = AnonymousClass000.A0q("messages_fts.content AS content", A0k);
        StringBuilder A0u5 = AnonymousClass000.A0u();
        AnonymousClass000.A1D("SELECT ", A0q, " FROM ", A0u5);
        A0u5.append("message_view AS message JOIN messages_fts AS messages_fts ON messages_fts.docid = message.sort_id");
        A05 = AnonymousClass000.A0q(" WHERE content MATCH ?", A0u5);
        StringBuilder A0u6 = AnonymousClass000.A0u();
        AnonymousClass000.A1D("SELECT ", A0q, " FROM ", A0u6);
        A0u6.append("available_message_view AS message JOIN messages_fts AS messages_fts ON messages_fts.docid = message.sort_id");
        A0u6.append(" WHERE content MATCH ? AND ");
        A04 = AnonymousClass000.A0q("chat_row_id = ?", A0u6);
        StringBuilder A0I3 = C36321k7.A0I("SELECT ", str, " FROM ", "message_view", A1C);
        A0I3.append("_id");
        A0I3.append(" IN ");
        A0B = AnonymousClass000.A0p("( \n   SELECT docid \n   FROM messages_fts AS messages_fts, available_message_view AS message \n   WHERE content MATCH ? AND messages_fts.docid = message._id\n   AND message.starred = 1 AND (message_type != '7'))\n", " ORDER BY _id DESC", A0I3);
        StringBuilder A0I4 = C36321k7.A0I("SELECT ", str, " FROM ", "message_view", A1C);
        A0I4.append("sort_id");
        A0I4.append(" IN ");
        C36321k7.A1O("( \n   SELECT docid \n   FROM message_ftsv2 AS messages_fts, available_message_view AS message \n   WHERE messages_fts.content MATCH ? AND messages_fts.docid = message.sort_id\n   AND message.starred = 1   AND (message_type != '7'))\n", " ORDER BY ", "sort_id", " DESC", A0I4);
        A0C = A0I4.toString();
        StringBuilder A0I5 = C36321k7.A0I("SELECT ", str, " FROM ", "available_message_view", A1C);
        A0I5.append("_id");
        A0I5.append(" IN ");
        A09 = AnonymousClass000.A0p("(SELECT docid FROM messages_fts AS messages_fts, message_view AS message WHERE chat_row_id = ? AND messages_fts.content MATCH ? AND messages_fts.docid = message._id AND message.starred = 1 AND (message_type != '7'))", " ORDER BY _id DESC", A0I5);
        StringBuilder A0I6 = C36321k7.A0I("SELECT ", str, " FROM ", "available_message_view AS message", A1C);
        A0I6.append("sort_id");
        A0I6.append(" IN ");
        A0I6.append("(SELECT docid FROM message_ftsv2 AS messages_fts, message_view AS message WHERE messages_fts.content MATCH ? AND messages_fts.docid = message.sort_id)");
        A0I6.append(A0r);
        A0I6.append("message.keep_in_chat = 1");
        A0I6.append(A0r);
        A08 = AnonymousClass000.A0p("(message_type != '7')", " ORDER BY sort_id DESC", A0I6);
    }
}
