package X;

/* renamed from: X.912  reason: invalid class name */
public enum AnonymousClass912 implements C22899AyB {
    STREAM_STOPPED_REASON_UNKNOWN(0),
    STREAM_STOPPED_REASON_USER_INITIATED(1),
    STREAM_STOPPED_REASON_SYSTEM_PREEMPT(2),
    STREAM_STOPPED_REASON_SYSTEM_SHUTDOWN(3),
    STREAM_STOPPED_REASON_BATTERY_LOW(4),
    STREAM_STOPPED_REASON_THERMAL_THRESHOLD(5),
    STREAM_STOPPED_REASON_INACTIVITY(6),
    STREAM_STOPPED_REASON_CAMERA_FAILURE(7),
    STREAM_STOPPED_REASON_DOFF(8),
    STREAM_STOPPED_REASON_CLOSE_ARMS(9),
    STREAM_STOPPED_REASON_AUDIO_FAILURE(10),
    STREAM_STOPPED_REASON_MOBILE_STREAM_ERROR(11),
    STREAM_STOPPED_REASON_PEAK_POWER_INTERRUPT(12),
    STREAM_STOPPED_REASON_USER_PAUSE(13),
    STREAM_STOPPED_REASON_TAMPER_DETECTED(14),
    STREAM_STOPPED_REASON_HARDWARE_TOGGLE(15),
    STREAM_STOPPED_REASON_SYSTEM_SHUTDOWN_BATTERY(16),
    UNRECOGNIZED(-1);
    
    public final int value;

    public final int BEY() {
        if (this != UNRECOGNIZED) {
            return this.value;
        }
        throw C165597tg.A0c();
    }

    /* access modifiers changed from: public */
    AnonymousClass912(int i) {
        this.value = i;
    }
}
