package X;

import com.whatsapp.voipcalling.camera.VoipLiteCamera;
import org.wawebrtc.MediaCodecVideoEncoder;

/* renamed from: X.91I  reason: invalid class name */
public enum AnonymousClass91I implements C22899AyB {
    GENERAL_CHAT_CREATE(188),
    GENERAL_CHAT_ADD(189),
    GENERAL_CHAT_AUTO_ADD_DISABLED(190),
    SUGGESTED_SUBGROUP_ANNOUNCE(191),
    BIZ_BOT_1P_MESSAGING_ENABLED(192),
    CHANGE_USERNAME(193),
    BIZ_COEX_PRIVACY_INIT_SELF(194),
    BIZ_COEX_PRIVACY_TRANSITION_SELF(195),
    SUPPORT_AI_EDUCATION(196),
    BIZ_BOT_3P_MESSAGING_ENABLED(197),
    REMINDER_SETUP_MESSAGE(198),
    REMINDER_SENT_MESSAGE(199),
    REMINDER_CANCEL_MESSAGE(200),
    BIZ_COEX_PRIVACY_INIT(201),
    BIZ_COEX_PRIVACY_TRANSITION(202),
    GROUP_DEACTIVATED(203);
    
    public final int value;

    public static AnonymousClass91I A01(String str, int i) {
        return new AnonymousClass91I(str, i, i);
    }

    /* access modifiers changed from: public */
    AnonymousClass91I(int i) {
        this.value = i;
    }

    public static AnonymousClass91I A00(int i) {
        switch (i) {
            case 0:
                return A31;
            case 1:
                return A2o;
            case 2:
                return A1H;
            case 3:
                return A1k;
            case 4:
                return A2Q;
            case 5:
                return A32;
            case 6:
                return A38;
            case 7:
                return A37;
            case 8:
                return A33;
            case 9:
                return A36;
            case 10:
                return A35;
            case 11:
                return A34;
            case 12:
                return A3A;
            case 13:
                return A39;
            case 14:
                return A3B;
            case 15:
                return A3C;
            case 16:
                return A3G;
            case 17:
                return A3D;
            case 18:
                return A3E;
            case 19:
                return A3F;
            case 20:
                return A1z;
            case 21:
                return A1y;
            case 22:
                return A1t;
            case 23:
                return A1u;
            case 24:
                return A1s;
            case 25:
                return A1x;
            case 26:
                return A1r;
            case 27:
                return A2A;
            case 28:
                return A2J;
            case 29:
                return A2I;
            case 30:
                return A2D;
            case 31:
                return A2E;
            case 32:
                return A2G;
            case 33:
                return A2C;
            case 34:
                return A14;
            case 35:
                return A13;
            case 36:
                return A15;
            case 37:
                return A1o;
            case 38:
                return A1f;
            case 39:
                return A1d;
            case 40:
                return A1C;
            case 41:
                return A1B;
            case 42:
                return A2L;
            case 43:
                return A23;
            case 44:
                return A1p;
            case 45:
                return A1A;
            case 46:
                return A19;
            case 47:
                return A2Y;
            case 48:
                return A2Z;
            case 49:
                return A2f;
            case 50:
                return A2g;
            case 51:
                return A2h;
            case 52:
                return A2d;
            case 53:
                return A2e;
            case 54:
                return A2S;
            case 55:
                return A2X;
            case 56:
                return A2W;
            case AnonymousClass8SU.IS_GROUP_HISTORY_MESSAGE_FIELD_NUMBER:
                return A2U;
            case 58:
                return A2V;
            case 59:
                return A2T;
            case AnonymousClass8SX.POLL_CREATION_MESSAGE_V2_FIELD_NUMBER:
                return A0L;
            case 61:
                return A0K;
            case 62:
                return A0B;
            case 63:
                return A0A;
            case 64:
                return A0D;
            case AnonymousClass8SX.SCHEDULED_CALL_EDIT_MESSAGE_FIELD_NUMBER:
                return A0C;
            case 66:
                return A0J;
            case AnonymousClass8SX.BOT_INVOKE_MESSAGE_FIELD_NUMBER:
                return A0I;
            case 68:
                return A2R;
            case AnonymousClass8SX.CALL_LOG_MESSSAGE_FIELD_NUMBER:
                return A1v;
            case AnonymousClass8SX.MESSAGE_HISTORY_BUNDLE_FIELD_NUMBER:
                return A2K;
            case AnonymousClass8SX.ENC_COMMENT_MESSAGE_FIELD_NUMBER:
                return A2B;
            case 72:
                return A1D;
            case 73:
                return A1b;
            case AnonymousClass8SX.LOTTIE_STICKER_MESSAGE_FIELD_NUMBER:
                return A3H;
            case AnonymousClass8SX.EVENT_MESSAGE_FIELD_NUMBER:
                return A1e;
            case AnonymousClass8SX.ENC_EVENT_RESPONSE_MESSAGE_FIELD_NUMBER:
                return A0N;
            case AnonymousClass8SX.COMMENT_MESSAGE_FIELD_NUMBER:
                return A0O;
            case AnonymousClass8SX.NEWSLETTER_ADMIN_INVITE_MESSAGE_FIELD_NUMBER:
                return A0P;
            case AnonymousClass8SX.EXTENDED_TEXT_MESSAGE_WITH_PARENT_KEY_FIELD_NUMBER:
                return A0Q;
            case AnonymousClass8SX.PLACEHOLDER_MESSAGE_FIELD_NUMBER:
                return A0T;
            case 81:
                return A0U;
            case AnonymousClass8SX.SECRET_ENCRYPTED_MESSAGE_FIELD_NUMBER:
                return A0X;
            case 83:
                return A0Y;
            case 84:
                return A0Z;
            case 85:
                return A0a;
            case 86:
                return A0b;
            case 87:
                return A0c;
            case 88:
                return A0d;
            case 89:
                return A0e;
            case VoipLiteCamera.DEFAULT_SUPERNOVA_ORIENTATION /*90*/:
                return A0f;
            case 91:
                return A0g;
            case 92:
                return A0h;
            case 93:
                return A0i;
            case 94:
                return A0j;
            case 95:
                return A0l;
            case 96:
                return A0m;
            case 97:
                return A0o;
            case 98:
                return A0p;
            case 99:
                return A0q;
            case 100:
                return A0r;
            case 101:
                return A0s;
            case 102:
                return A0t;
            case 103:
                return A0u;
            case 104:
                return A0v;
            case 105:
                return A0w;
            case 106:
                return A0x;
            case 107:
                return A0y;
            case C65953Uc.A03:
                return A0z;
            case 109:
                return A10;
            case 110:
                return A11;
            case 111:
                return A12;
            case 112:
                return A0R;
            case 113:
                return A0S;
            case 114:
                return A0V;
            case 115:
                return A0W;
            case 116:
                return A0k;
            case 117:
                return A0n;
            case 118:
                return A1g;
            case 119:
                return A21;
            case 120:
                return A20;
            case 121:
                return A1q;
            case 122:
                return A0M;
            case 123:
                return A1j;
            case 124:
                return A30;
            case 125:
                return A2z;
            case 126:
                return A0F;
            case 127:
                return A0E;
            case 128:
                return A0H;
            case 129:
                return A0G;
            case 130:
                return A1a;
            case 131:
                return A1c;
            case 132:
                return A01;
            case 133:
                return A24;
            case 134:
                return A1N;
            case 135:
                return A1Q;
            case 136:
                return A1R;
            case 137:
                return A1X;
            case 138:
                return A1Y;
            case 139:
                return A1Z;
            case 140:
                return A29;
            case 141:
                return A2H;
            case 142:
                return A1K;
            case 143:
                return A1i;
            case MediaCodecVideoEncoder.MIN_ENCODER_HEIGHT:
                return A26;
            case 145:
                return A25;
            case 146:
                return A2M;
            case 147:
                return A1W;
            case 148:
                return A1V;
            case 149:
                return A1S;
            case 150:
                return A1O;
            case 151:
                return A2F;
            case 152:
                return A2O;
            case 153:
                return A2P;
            case 154:
                return A04;
            case 155:
                return A1G;
            case 156:
                return A1F;
            case 157:
                return A18;
            case 158:
                return A1T;
            case 159:
                return A16;
            case 160:
                return A05;
            case 161:
                return A17;
            case 162:
                return A2q;
            case 163:
                return A1M;
            case 164:
                return A1L;
            case 165:
                return A2v;
            case 166:
                return A2w;
            case 167:
                return A1P;
            case 168:
                return A1U;
            case 169:
                return A2s;
            case 170:
                return A2t;
            case 171:
                return A28;
            case 172:
                return A27;
            case 173:
                return A1J;
            case 174:
                return A2r;
            case 175:
                return A2j;
            case MediaCodecVideoEncoder.MIN_ENCODER_WIDTH:
                return A1I;
            case 177:
                return A2i;
            case 178:
                return A2c;
            case 179:
                return A2a;
            case 180:
                return A2b;
            case 181:
                return A2N;
            case 182:
                return A2n;
            case 183:
                return A1h;
            case 184:
                return A2p;
            case 185:
                return A2u;
            case 186:
                return A1w;
            case 188:
                return GENERAL_CHAT_CREATE;
            case 189:
                return GENERAL_CHAT_ADD;
            case 190:
                return GENERAL_CHAT_AUTO_ADD_DISABLED;
            case 191:
                return SUGGESTED_SUBGROUP_ANNOUNCE;
            case 192:
                return BIZ_BOT_1P_MESSAGING_ENABLED;
            case 193:
                return CHANGE_USERNAME;
            case 194:
                return BIZ_COEX_PRIVACY_INIT_SELF;
            case 195:
                return BIZ_COEX_PRIVACY_TRANSITION_SELF;
            case 196:
                return SUPPORT_AI_EDUCATION;
            case 197:
                return BIZ_BOT_3P_MESSAGING_ENABLED;
            case 198:
                return REMINDER_SETUP_MESSAGE;
            case 199:
                return REMINDER_SENT_MESSAGE;
            case 200:
                return REMINDER_CANCEL_MESSAGE;
            case 201:
                return BIZ_COEX_PRIVACY_INIT;
            case 202:
                return BIZ_COEX_PRIVACY_TRANSITION;
            case 203:
                return GROUP_DEACTIVATED;
            default:
                return null;
        }
    }

    public final int BEY() {
        return this.value;
    }
}
