package X;

import com.whatsapp.accountsync.di.AccountSyncModule;
import com.whatsapp.addons.di.AddOnBridgeModule;
import com.whatsapp.authcommon.di.CommonModule;
import com.whatsapp.authgraphql.di.UnifiedAuthenticationModule;
import com.whatsapp.avatar.di.AvatarModule;
import com.whatsapp.biz.BusinessProductModule;
import com.whatsapp.biz.di.DCEncryptedModule;
import com.whatsapp.bridge.wfs.di.WfsProductReleaseModule;
import com.whatsapp.chatinfo.di.ActivityModule;
import com.whatsapp.community.di.CommunityNotificationModule;
import com.whatsapp.conversation.conversationrow.nativeflow.NativeFlowActionModule;
import com.whatsapp.conversation.di.ConversationUiModule;
import com.whatsapp.core.di.TimeModule;
import com.whatsapp.cron.di.CronModule;
import com.whatsapp.ctwa.di.CtwaModule;
import com.whatsapp.dailyevent.di.DailyEventModule;
import com.whatsapp.data.di.QuotedMessageStoreModule;
import com.whatsapp.data.migration.di.ForceMigrationModule;
import com.whatsapp.data.transactionlock.TransactionLockModule;
import com.whatsapp.dbmigration.di.DatabaseMigrationModule;
import com.whatsapp.di.CompanionModeModule;
import com.whatsapp.di.JidMapperProviderModule;
import com.whatsapp.di.MigrationModule;
import com.whatsapp.di.SearchModule;
import com.whatsapp.dmapreview.di.PreviewSubsystemModule;
import com.whatsapp.ephemeral.di.EphemeralProductModule;
import com.whatsapp.event.EventChatInfoModule;
import com.whatsapp.expressionstray.di.EmojiImageViewLoaderModule;
import com.whatsapp.fmessage.di.FMessageRegistrationsModule;
import com.whatsapp.fmessage.factory.di.FMessageFactoryModule;
import com.whatsapp.fmessage.forward.di.FMessageForwardingSubsystemModule;
import com.whatsapp.fmessage.platform.di.FMessagePlatformModule;
import com.whatsapp.fmessage.platform.registration.di.FMessagePlatformRegistrationModule;
import com.whatsapp.fmessage.systemmessage.platform.registration.di.SystemMessagePlatformRegistrationModule;
import com.whatsapp.gifsearch.di.GifSearchModule;
import com.whatsapp.indiaupi.di.IndiaUpiModule;
import com.whatsapp.integrity.di.IntegrityModule;
import com.whatsapp.integritysignals.di.IntegritySignalsModule;
import com.whatsapp.media.dailyusage.di.MediaDailyUsageModule;
import com.whatsapp.notification.di.OtpNotificationModule;
import com.whatsapp.p2mlite.di.P2mLiteModule;
import com.whatsapp.payments.di.IndiaUpiInfraModule;
import com.whatsapp.pininchat.subsystem.di.PinInChatSubsystemModule;
import com.whatsapp.preloads.di.PreloadsReleaseModule;
import com.whatsapp.reply.subsystem.di.ReplySubsystemModule;
import com.whatsapp.stickers.di.RecentStickersModule;
import com.whatsapp.systemmessage.di.SystemMessageRegistrationsModule;
import com.whatsapp.systemmessage.factory.di.SystemMessageFactoryModule;
import com.whatsapp.wabloks.commerce.di.CommerceBloksModule;
import com.whatsapp.wabloks.commerce.phoenix.external.directconnection.ExtensionsProductModule;
import com.whatsapp.waffle.accountlinking.di.WfalProdInfraModule;
import com.whatsapp.waffle.wfac.di.WfacProductReleaseModule;
import com.whatsapp.waquickpromotionsdk.filters.di.WaQuickPromotionFilterModule;
import com.whatsapp.webquery.di.WebQueryModule;
import com.whatsapp.workmanager.WaWorkManagerModule;
import com.whatsapp.xfamily.graphql.di.XFamilyGQLModule;

/* renamed from: X.0v8  reason: invalid class name and case insensitive filesystem */
public final class C19490v8 {
    public AccountSyncModule A00;
    public AddOnBridgeModule A01;
    public CommonModule A02;
    public UnifiedAuthenticationModule A03;
    public AvatarModule A04;
    public BusinessProductModule A05;
    public DCEncryptedModule A06;
    public WfsProductReleaseModule A07;
    public ActivityModule A08;
    public CommunityNotificationModule A09;
    public NativeFlowActionModule A0A;
    public ConversationUiModule A0B;
    public TimeModule A0C;
    public CronModule A0D;
    public CtwaModule A0E;
    public DailyEventModule A0F;
    public QuotedMessageStoreModule A0G;
    public ForceMigrationModule A0H;
    public TransactionLockModule A0I;
    public DatabaseMigrationModule A0J;
    public CompanionModeModule A0K;
    public JidMapperProviderModule A0L;
    public MigrationModule A0M;
    public SearchModule A0N;
    public PreviewSubsystemModule A0O;
    public EphemeralProductModule A0P;
    public EventChatInfoModule A0Q;
    public EmojiImageViewLoaderModule A0R;
    public FMessageRegistrationsModule A0S;
    public FMessageFactoryModule A0T;
    public FMessageForwardingSubsystemModule A0U;
    public FMessagePlatformModule A0V;
    public FMessagePlatformRegistrationModule A0W;
    public SystemMessagePlatformRegistrationModule A0X;
    public GifSearchModule A0Y;
    public IndiaUpiModule A0Z;
    public IntegrityModule A0a;
    public IntegritySignalsModule A0b;
    public MediaDailyUsageModule A0c;
    public OtpNotificationModule A0d;
    public P2mLiteModule A0e;
    public IndiaUpiInfraModule A0f;
    public PinInChatSubsystemModule A0g;
    public PreloadsReleaseModule A0h;
    public ReplySubsystemModule A0i;
    public RecentStickersModule A0j;
    public SystemMessageRegistrationsModule A0k;
    public SystemMessageFactoryModule A0l;
    public CommerceBloksModule A0m;
    public ExtensionsProductModule A0n;
    public WfalProdInfraModule A0o;
    public WfacProductReleaseModule A0p;
    public WaQuickPromotionFilterModule A0q;
    public WebQueryModule A0r;
    public WaWorkManagerModule A0s;
    public XFamilyGQLModule A0t;
    public C19500v9 A0u;
}
