package X;

import java.util.Objects;
import java.util.Set;

/* renamed from: X.1Tx  reason: invalid class name and case insensitive filesystem */
public class C28761Tx extends AnonymousClass08K {
    public final /* synthetic */ C28731Tu A00;
    public final /* synthetic */ C28751Tw A01;

    public C28761Tx(C28731Tu r1, C28751Tw r2) {
        this.A01 = r2;
        this.A00 = r1;
    }

    public AnonymousClass04R A02(AnonymousClass08M r6, Class cls, String str) {
        C28771Tz r3 = new C28771Tz();
        C28731Tu r1 = this.A00;
        Objects.requireNonNull(r6);
        r1.A00 = r6;
        Objects.requireNonNull(r3);
        r1.A01 = r3;
        AnonymousClass08M r4 = r1.A00;
        Class<AnonymousClass08M> cls2 = AnonymousClass08M.class;
        if (r4 != null) {
            AnonymousClass1U1 r42 = (AnonymousClass1U1) AnonymousClass1U0.class.cast(new AnonymousClass1U1(r4, r1.A02, r1.A03));
            C20090x0 builderWithExpectedSize = C20070wy.builderWithExpectedSize(173);
            builderWithExpectedSize.put("com.whatsapp.calling.chatmessages.AdhocParticipantBottomSheetViewModel", r42.A00);
            builderWithExpectedSize.put("com.whatsapp.status.advertise.AdvertiseViewModel", r42.A01);
            builderWithExpectedSize.put("com.whatsapp.qrcode.AgentDeviceLoginViewModel", r42.A02);
            builderWithExpectedSize.put("com.whatsapp.conversationslist.ArchiveHeaderViewModel", r42.A03);
            builderWithExpectedSize.put("com.whatsapp.calling.lightweightcalling.viewmodel.AudioChatCallingViewModel", r42.A04);
            builderWithExpectedSize.put("com.whatsapp.expressionstray.avatars.AvatarExpressionsViewModel", r42.A05);
            builderWithExpectedSize.put("com.whatsapp.avatar.home.AvatarHomeViewModel", r42.A0A);
            builderWithExpectedSize.put("com.whatsapp.avatar.profilephoto.AvatarProfilePhotoViewModel", r42.A0B);
            builderWithExpectedSize.put("com.whatsapp.userban.ui.viewmodel.BanAppealViewModel", r42.A0C);
            builderWithExpectedSize.put("com.whatsapp.report.activity.banreport.BanReportViewModel", r42.A0E);
            builderWithExpectedSize.put("com.whatsapp.blockbusiness.blockreasonlist.BlockReasonListViewModel", r42.A0F);
            builderWithExpectedSize.put("com.whatsapp.wabloks.ui.bottomsheet.BloksCDSBottomSheetViewModel", r42.A0G);
            builderWithExpectedSize.put("com.whatsapp.bonsai.chatinfo.BonsaiChatInfoViewModel", r42.A0H);
            builderWithExpectedSize.put("com.whatsapp.bonsai.BonsaiConversationTitleViewModel", r42.A0I);
            builderWithExpectedSize.put("com.whatsapp.bonsai.discovery.BonsaiDiscoveryViewModel", r42.A0J);
            builderWithExpectedSize.put("com.whatsapp.bonsai.prompts.BonsaiPromptsViewModel", r42.A0K);
            builderWithExpectedSize.put("com.whatsapp.bonsai.BonsaiSystemMessageBottomSheetViewModel", r42.A0L);
            builderWithExpectedSize.put("com.whatsapp.bonsai.embodiment.BotEmbodimentViewModel", r42.A0M);
            builderWithExpectedSize.put("com.whatsapp.calling.controls.viewmodel.BottomSheetViewModel", r42.A0N);
            builderWithExpectedSize.put("com.whatsapp.payments.ui.viewmodel.BrazilAddPixKeyViewModel", r42.A0O);
            builderWithExpectedSize.put("com.whatsapp.payments.ui.viewmodel.BrazilAddPixSelectionViewModel", r42.A0P);
            builderWithExpectedSize.put("com.whatsapp.payments.ui.viewmodel.BrazilHostedPaymentPageViewModel", r42.A0Q);
            builderWithExpectedSize.put("com.whatsapp.payments.ui.viewmodel.BrazilIncomeCollectionViewModel", r42.A0R);
            builderWithExpectedSize.put("com.whatsapp.payments.ui.viewmodel.BrazilPixKeySettingViewModel", r42.A0S);
            builderWithExpectedSize.put("com.whatsapp.report.BusinessActivityReportViewModel", r42.A0T);
            builderWithExpectedSize.put("com.whatsapp.businessapisearch.viewmodel.BusinessApiSearchActivityViewModel", r42.A0U);
            builderWithExpectedSize.put("com.whatsapp.biz.compliance.viewmodel.BusinessComplianceViewModel", r42.A0V);
            builderWithExpectedSize.put("com.whatsapp.businessdirectory.viewmodel.BusinessDirectoryActivityViewModel", r42.A0W);
            builderWithExpectedSize.put("com.whatsapp.businessdirectory.viewmodel.BusinessDirectoryConsumerHomeViewModel", r42.A0X);
            builderWithExpectedSize.put("com.whatsapp.businessdirectory.viewmodel.BusinessDirectoryContextualSearchViewModel", r42.A0Y);
            builderWithExpectedSize.put("com.whatsapp.businessdirectory.viewmodel.BusinessDirectoryEducationNuxViewModel", r42.A0Z);
            builderWithExpectedSize.put("com.whatsapp.businessdirectory.viewmodel.BusinessDirectoryFrequentContactedViewModel", r42.A0a);
            builderWithExpectedSize.put("com.whatsapp.businessdirectory.viewmodel.BusinessDirectoryPopularApiBusinessesViewModel", r42.A0b);
            builderWithExpectedSize.put("com.whatsapp.community.communityInfo.viewModels.CAGInfoChatLockViewModel", r42.A0c);
            builderWithExpectedSize.put("com.whatsapp.community.communityInfo.CAGInfoViewModel", r42.A0d);
            builderWithExpectedSize.put("com.whatsapp.calling.avatar.viewmodel.CallAvatarViewModel", r42.A0e);
            builderWithExpectedSize.put("com.whatsapp.calling.controls.viewmodel.CallControlButtonsViewModel", r42.A0f);
            builderWithExpectedSize.put("com.whatsapp.calling.callgrid.viewmodel.CallGridViewModel", r42.A0g);
            builderWithExpectedSize.put("com.whatsapp.calling.callheader.viewmodel.CallHeaderViewModel", r42.A0h);
            builderWithExpectedSize.put("com.whatsapp.calling.calllink.viewmodel.CallLinkViewModel", r42.A0i);
            builderWithExpectedSize.put("com.whatsapp.calling.chatmessages.CallLogMessageParticipantBottomSheetViewModel", r42.A0j);
            builderWithExpectedSize.put("com.whatsapp.calling.callrating.viewmodel.CallRatingViewModel", r42.A0k);
            builderWithExpectedSize.put("com.whatsapp.contact.picker.viewmodels.CallSuggestionsViewModel", r42.A0l);
            builderWithExpectedSize.put("com.whatsapp.calling.callhistory.viewmodel.CallsHistoryFragmentV2ViewModel", r42.A0m);
            builderWithExpectedSize.put("com.whatsapp.catalogcategory.view.viewmodel.CatalogAllCategoryViewModel", r42.A0n);
            builderWithExpectedSize.put("com.whatsapp.catalogcategory.view.viewmodel.CatalogCategoryGroupsViewModel", r42.A0o);
            builderWithExpectedSize.put("com.whatsapp.catalogcategory.view.viewmodel.CatalogCategoryTabsViewModel", r42.A0p);
            builderWithExpectedSize.put("com.whatsapp.catalogsearch.view.viewmodel.CatalogSearchViewModel", r42.A0q);
            builderWithExpectedSize.put("com.whatsapp.chatlock.dialogs.helperflow.ChatLockHelperBottomSheetViewModel", r42.A0r);
            builderWithExpectedSize.put("com.whatsapp.migration.transfer.ui.ChatTransferViewModel", r42.A0s);
            builderWithExpectedSize.put("com.whatsapp.authgraphql.ui.CommonViewModel", r42.A0t);
            builderWithExpectedSize.put("com.whatsapp.community.communitysettings.viewmodel.CommunitySettingsViewModel", r42.A0u);
            builderWithExpectedSize.put("com.whatsapp.companionmode.registration.CompanionRegistrationViewModel", r42.A0v);
            builderWithExpectedSize.put("com.whatsapp.biz.product.viewmodel.ComplianceInfoViewModel", r42.A0w);
            builderWithExpectedSize.put("com.whatsapp.datasharingdisclosure.ui.ConsumerDisclosureViewModel", r42.A0x);
            builderWithExpectedSize.put("com.whatsapp.community.ConversationCommunityViewModel", r42.A0y);
            builderWithExpectedSize.put("com.whatsapp.conversationslist.filter.ConversationFilterViewModel", r42.A0z);
            builderWithExpectedSize.put("com.whatsapp.conversation.viewmodel.ConversationSearchViewModel", r42.A10);
            builderWithExpectedSize.put("com.whatsapp.conversation.viewmodel.ConversationTitleViewModel", r42.A11);
            builderWithExpectedSize.put("com.whatsapp.conversationslist.ConversationsSuggestedContactsViewModel", r42.A12);
            builderWithExpectedSize.put("com.whatsapp.countrygating.viewmodel.CountryGatingViewModel", r42.A13);
            builderWithExpectedSize.put("com.whatsapp.countries.CountryListViewModel", r42.A14);
            builderWithExpectedSize.put("com.whatsapp.status.crossposting.CrossPostingUpdatesViewModel", r42.A15);
            builderWithExpectedSize.put("com.whatsapp.status.advertise.CtwaStatusUpsellBottomSheetTriggerViewModel", r42.A16);
            builderWithExpectedSize.put("com.whatsapp.expressionstray.emoji.EmojiExpressionsViewModel", r42.A18);
            builderWithExpectedSize.put("com.whatsapp.backup.encryptedbackup.EncBackupViewModel", r42.A19);
            builderWithExpectedSize.put("com.whatsapp.product.newsletterenforcements.enforcedmessages.EnforcedMessagesViewModel", r42.A1A);
            builderWithExpectedSize.put("com.whatsapp.registration.entercode.EnterCodeViewModel", r42.A1B);
            builderWithExpectedSize.put("com.whatsapp.registration.phonenumberentry.viewmodel.ExistViewModel", r42.A1C);
            builderWithExpectedSize.put("com.whatsapp.migration.export.ui.ExportMigrationViewModel", r42.A1D);
            builderWithExpectedSize.put("com.whatsapp.expressionstray.conversation.ExpressionsKeyboardViewModel", r42.A1E);
            builderWithExpectedSize.put("com.whatsapp.expressionstray.ExpressionsSearchViewModel", r42.A1F);
            builderWithExpectedSize.put("com.whatsapp.calling.favorite.calllist.FavoriteCallListViewModel", r42.A1G);
            builderWithExpectedSize.put("com.whatsapp.calling.favorite.FavoritePickerViewModel", r42.A1H);
            builderWithExpectedSize.put("com.whatsapp.extensions.phoenix.viewmodel.FlowsFooterViewModel", r42.A1J);
            builderWithExpectedSize.put("com.whatsapp.gallerypicker.viewmodels.GalleryPickerViewModel", r42.A1K);
            builderWithExpectedSize.put("com.whatsapp.gallery.viewmodel.GalleryViewModel", r42.A1L);
            builderWithExpectedSize.put("com.whatsapp.wabloks.base.GenericBkLayoutViewModelWithReload", r42.A1N);
            builderWithExpectedSize.put("com.whatsapp.wabloks.base.GenericBkLayoutViewModel", r42.A1M);
            builderWithExpectedSize.put("com.whatsapp.expressionstray.gifs.GifExpressionsSearchViewModel", r42.A1P);
            builderWithExpectedSize.put("com.whatsapp.backup.google.viewmodel.GoogleDriveNewUserSetupViewModel", r42.A1Q);
            builderWithExpectedSize.put("com.whatsapp.migration.android.view.GoogleMigrateImporterViewModel", r42.A1R);
            builderWithExpectedSize.put("com.whatsapp.calling.callhistory.group.GroupCallParticipantSuggestionsViewModel", r42.A1S);
            builderWithExpectedSize.put("com.whatsapp.calling.psa.viewmodel.GroupCallPsaViewModel", r42.A1T);
            builderWithExpectedSize.put("com.whatsapp.group.HistorySettingViewModel", r42.A1U);
            builderWithExpectedSize.put("com.whatsapp.home.HomeViewModel", r42.A1V);
            builderWithExpectedSize.put("com.whatsapp.inappbugreporting.InAppBugReportingViewModel", r42.A1W);
            builderWithExpectedSize.put("com.whatsapp.calling.callgrid.viewmodel.InCallBannerViewModel", r42.A1X);
            builderWithExpectedSize.put("com.whatsapp.payments.ui.viewmodel.IndiaPaymentSettingsViewModel", r42.A1Y);
            builderWithExpectedSize.put("com.whatsapp.payments.ui.international.IndiaUpiInternationalActivationViewModel", r42.A1Z);
            builderWithExpectedSize.put("com.whatsapp.payments.ui.international.IndiaUpiInternationalValidateQrViewModel", r42.A1a);
            builderWithExpectedSize.put("com.whatsapp.payments.ui.viewmodel.IndiaUpiMandateHistoryViewModel", r42.A1b);
            builderWithExpectedSize.put("com.whatsapp.payments.ui.mapper.register.IndiaUpiMapperLinkViewModel", r42.A1c);
            builderWithExpectedSize.put("com.whatsapp.payments.ui.viewmodel.IndiaUpiNumberSettingsViewModel", r42.A1d);
            builderWithExpectedSize.put("com.whatsapp.payments.ui.viewmodel.IndiaUpiPauseMandateViewModel", r42.A1e);
            builderWithExpectedSize.put("com.whatsapp.payments.ui.viewmodel.IndiaUpiPaymentTransactionConfirmationBottomSheetViewModel", r42.A1f);
            builderWithExpectedSize.put("com.whatsapp.payments.viewmodel.IndiaUpiSecureQrCodeViewModel", r42.A1g);
            builderWithExpectedSize.put("com.whatsapp.interopui.compose.InteropComposeEnterInfoViewModel", r42.A1h);
            builderWithExpectedSize.put("com.whatsapp.interopui.compose.InteropComposeSelectIntegratorViewModel", r42.A1i);
            builderWithExpectedSize.put("com.whatsapp.interopui.optin.InteropOptInSelectIntegratorsViewModel", r42.A1j);
            builderWithExpectedSize.put("com.whatsapp.interopui.setting.InteropSettingsViewModel", r42.A1k);
            builderWithExpectedSize.put("com.whatsapp.conversationslist.InteropViewModel", r42.A1l);
            builderWithExpectedSize.put("com.whatsapp.contact.picker.viewmodels.InviteNonWhatsAppContactPickerViewModel", r42.A1m);
            builderWithExpectedSize.put("com.whatsapp.calling.callconfirmationsheet.vm.LGCCallConfirmationSheetViewModel", r42.A1n);
            builderWithExpectedSize.put("com.whatsapp.companiondevice.LinkedDeviceEditDeviceViewModel", r42.A1o);
            builderWithExpectedSize.put("com.whatsapp.companiondevice.LinkedDeviceEnterNicknameViewModel", r42.A1p);
            builderWithExpectedSize.put("com.whatsapp.companiondevice.LinkedDevicesSharedViewModel", r42.A1q);
            builderWithExpectedSize.put("com.whatsapp.companiondevice.LinkedDevicesViewModel", r42.A1r);
            builderWithExpectedSize.put("com.whatsapp.businessdirectory.viewmodel.LocationOptionPickerViewModel", r42.A1s);
            builderWithExpectedSize.put("com.whatsapp.magicmod.popup.MagicModPopupViewModel", r42.A1t);
            builderWithExpectedSize.put("com.whatsapp.gallery.viewmodel.MediaGalleryFragmentViewModel", r42.A1u);
            builderWithExpectedSize.put("com.whatsapp.mediaview.MediaViewCurrentMessageViewModel", r42.A1v);
            builderWithExpectedSize.put("com.whatsapp.calling.callgrid.viewmodel.MenuBottomSheetViewModel", r42.A1w);
            builderWithExpectedSize.put("com.whatsapp.conversation.conversationrow.message.MessageDetailsViewModel", r42.A1x);
            builderWithExpectedSize.put("com.whatsapp.conversation.conversationrow.messagerating.MessageRatingViewModel", r42.A1y);
            builderWithExpectedSize.put("com.whatsapp.conversation.conversationrow.MessageSelectionViewModel", r42.A1z);
            builderWithExpectedSize.put("com.whatsapp.calling.banner.viewmodel.MinimizedCallBannerViewModel", r42.A20);
            builderWithExpectedSize.put("com.whatsapp.mute.ui.MuteDialogViewModel", r42.A21);
            builderWithExpectedSize.put("com.whatsapp.registration.accountdefence.NewDeviceConfirmationRegistrationViewModel", r42.A22);
            builderWithExpectedSize.put("com.whatsapp.product.newsletterenforcements.geosuspend.NewsletterGeosuspensionInfoViewModel", r42.A23);
            builderWithExpectedSize.put("com.whatsapp.product.integrityappeals.NewsletterRequestReviewViewModel", r42.A24);
            builderWithExpectedSize.put("com.whatsapp.product.newsletterenforcements.suspension.NewsletterSuspensionInfoViewModel", r42.A25);
            builderWithExpectedSize.put("com.whatsapp.product.newsletterenforcements.userreports.NewsletterUserReportsViewModel", r42.A26);
            builderWithExpectedSize.put("com.whatsapp.settings.notificationsandsounds.NotificationsAndSoundsViewModel", r42.A27);
            builderWithExpectedSize.put("com.whatsapp.calling.callgrid.viewmodel.OrientationViewModel", r42.A28);
            builderWithExpectedSize.put("com.whatsapp.calling.controls.viewmodel.ParticipantsListViewModel", r42.A29);
            builderWithExpectedSize.put("com.whatsapp.payments.ui.viewmodel.PaymentIncentiveViewModel", r42.A2A);
            builderWithExpectedSize.put("com.whatsapp.payments.ui.viewmodel.PaymentMerchantAccountViewModel", r42.A2B);
            builderWithExpectedSize.put("com.whatsapp.pininchat.banner.PinInChatBannerViewModel", r42.A2C);
            builderWithExpectedSize.put("com.whatsapp.polls.PollCreatorViewModel", r42.A2D);
            builderWithExpectedSize.put("com.whatsapp.privacy.disclosure.ui.PrivacyDisclosureContainerViewModel", r42.A2E);
            builderWithExpectedSize.put("com.whatsapp.biz.product.viewmodel.ProductBottomSheetViewModel", r42.A2F);
            builderWithExpectedSize.put("com.whatsapp.quickactionbar.viewmodel.QuickActionBarViewModel", r42.A2G);
            builderWithExpectedSize.put("com.whatsapp.reactions.ReactionsTrayViewModel", r42.A2H);
            builderWithExpectedSize.put("com.whatsapp.spamreport.ReportSpamDialogViewModel", r42.A2I);
            builderWithExpectedSize.put("com.whatsapp.pnh.RequestPhoneNumberViewModel", r42.A2J);
            builderWithExpectedSize.put("com.whatsapp.backup.google.viewmodel.RestoreFromBackupViewModel", r42.A2K);
            builderWithExpectedSize.put("com.whatsapp.registration.timers.RetryCodeCountdownTimersViewModel", r42.A2L);
            builderWithExpectedSize.put("com.whatsapp.calling.screenshare.ScreenShareViewModel", r42.A2M);
            builderWithExpectedSize.put("com.whatsapp.expressionstray.stickers.funstickers.viewmodels.SearchFunStickersViewModel", r42.A2N);
            builderWithExpectedSize.put("com.whatsapp.conversation.selection.SelectedImageAlbumViewModel", r42.A2O);
            builderWithExpectedSize.put("com.whatsapp.settings.SettingsAccountViewModel", r42.A2P);
            builderWithExpectedSize.put("com.whatsapp.settings.SettingsChatViewModel", r42.A2Q);
            builderWithExpectedSize.put("com.whatsapp.settings.SettingsDataUsageViewModel", r42.A2R);
            builderWithExpectedSize.put("com.whatsapp.backup.google.viewmodel.SettingsGoogleDriveViewModel", r42.A2S);
            builderWithExpectedSize.put("com.whatsapp.settings.SettingsPasskeysViewModel", r42.A2T);
            builderWithExpectedSize.put("com.whatsapp.settings.SettingsPrivacyCameraEffectsViewModel", r42.A2U);
            builderWithExpectedSize.put("com.whatsapp.settings.SettingsSetupUserProxyViewModel", r42.A2V);
            builderWithExpectedSize.put("com.whatsapp.settings.SettingsUserProxyViewModel", r42.A2W);
            builderWithExpectedSize.put("com.whatsapp.conversation.conversationrow.viewmodel.SharePhoneNumberRowViewModel", r42.A2X);
            builderWithExpectedSize.put("com.whatsapp.chatinfo.SharePhoneNumberViewModel", r42.A2Y);
            builderWithExpectedSize.put("com.whatsapp.biz.catalog.viewmodel.ShareProductViewModel", r42.A2Z);
            builderWithExpectedSize.put("com.whatsapp.shops.ShopsBkLayoutViewModel", r42.A2a);
            builderWithExpectedSize.put("com.whatsapp.shops.ShopsProductPreviewFragmentViewModel", r42.A2b);
            builderWithExpectedSize.put("com.whatsapp.status.archive.StatusArchiveSettingsViewModel", r42.A2c);
            builderWithExpectedSize.put("com.whatsapp.mediacomposer.viewmodel.StickerComposerViewModel", r42.A2d);
            builderWithExpectedSize.put("com.whatsapp.expressionstray.stickers.StickerExpressionsViewModel", r42.A2e);
            builderWithExpectedSize.put("com.whatsapp.stickers.info.bottomsheet.StickerInfoViewModel", r42.A2f);
            builderWithExpectedSize.put("com.whatsapp.inappsupport.ui.SupportAiViewModel", r42.A2h);
            builderWithExpectedSize.put("com.whatsapp.inappsupport.ui.SupportBkLayoutViewModel", r42.A2i);
            builderWithExpectedSize.put("com.whatsapp.conversation.viewmodel.SurveyViewModel", r42.A2j);
            builderWithExpectedSize.put("com.whatsapp.tosgating.viewmodel.ToSGatingViewModel", r42.A2k);
            builderWithExpectedSize.put("com.whatsapp.media.utwonet.UTwoNetViewModel", r42.A2l);
            builderWithExpectedSize.put("com.whatsapp.mediacomposer.doodle.universaltoolpicker.UniversalToolPickerViewModel", r42.A2m);
            builderWithExpectedSize.put("com.whatsapp.calling.schedulecall.upcomingcalls.viewmodel.UpcomingActivityViewModel", r42.A2n);
            builderWithExpectedSize.put("com.whatsapp.status.advertise.UpdatesAdvertiseViewModel", r42.A2o);
            builderWithExpectedSize.put("com.whatsapp.profile.UsernameViewModel", r42.A2p);
            builderWithExpectedSize.put("com.whatsapp.biz.catalog.view.variants.VariantsCarouselFragmentViewModel", r42.A2q);
            builderWithExpectedSize.put("com.whatsapp.calling.lightweightcalling.viewmodel.VoiceChatBottomSheetViewModel", r42.A2r);
            builderWithExpectedSize.put("com.whatsapp.calling.callgrid.viewmodel.VoiceChatGridViewModel", r42.A2s);
            builderWithExpectedSize.put("com.whatsapp.wabloks.commerce.ui.viewmodel.WaBkExtensionsLayoutViewModel", r42.A2t);
            builderWithExpectedSize.put("com.whatsapp.extensions.webview.viewmodel.WaFlowsViewModel", r42.A2u);
            builderWithExpectedSize.put("com.whatsapp.waffle.wfac.ui.WfacBanViewModel", r42.A2v);
            C20070wy build = builderWithExpectedSize.build();
            String name = cls.getName();
            AnonymousClass004 r0 = (AnonymousClass004) build.get(name);
            if (r0 != null) {
                AnonymousClass04R r2 = (AnonymousClass04R) r0.get();
                AnonymousClass1U3 r12 = new AnonymousClass1U3(r3);
                Set set = r2.A01;
                synchronized (set) {
                    set.add(r12);
                }
                return r2;
            }
            StringBuilder sb = new StringBuilder();
            sb.append("Expected the @HiltViewModel-annotated class '");
            sb.append(name);
            sb.append("' to be available in the multi-binding of @HiltViewModelMap but none was found.");
            throw new IllegalStateException(sb.toString());
        }
        StringBuilder sb2 = new StringBuilder();
        sb2.append(cls2.getCanonicalName());
        sb2.append(" must be set");
        throw new IllegalStateException(sb2.toString());
    }
}
