package X;

/* renamed from: X.2xB  reason: invalid class name and case insensitive filesystem */
public abstract class C56892xB {
    public static final String A00;
    public static final String A01;
    public static final String A02;
    public static final String A03;
    public static final String A04;
    public static final String A05;
    public static final String A06;
    public static final String A07;
    public static final String A08;
    public static final String A09;
    public static final String A0A;
    public static final String A0B;
    public static final String A0C;
    public static final String A0D;
    public static final String A0E;
    public static final String A0F;
    public static final String A0G;
    public static final String A0H;
    public static final String A0I;

    public static void A00(StringBuilder sb, String str) {
        sb.append(AnonymousClass1M2.A01("message", new String[]{str}));
        sb.append(",");
    }

    static {
        StringBuilder A0u = AnonymousClass000.A0u();
        A0u.append("SELECT ");
        String[] strArr = C56842wy.A03;
        C36361kB.A1R("message", A0u, strArr);
        A0u.append(" FROM ");
        A0u.append("available_message_view AS message");
        A0u.append(" LEFT JOIN ");
        A0u.append("chat");
        A0u.append(" AS chat ON message.");
        A0u.append("chat_row_id");
        A0u.append(" = chat.");
        String A1C = C36431kI.A1C("_id", A0u);
        A0u.append("message.message_type IN ('2', '1', '25', '3', '81', '28', '13', '29', '9', '26')");
        A0u.append(" AND (chat.chat_lock = 0");
        A02 = AnonymousClass000.A0q(" OR chat.chat_lock is NULL)", A0u);
        StringBuilder A0v = AnonymousClass000.A0v("SELECT ");
        C36361kB.A1R("message", A0v, strArr);
        A0v.append(", ");
        A0v.append("file_size");
        A0v.append(" FROM ");
        A0v.append("message_media AS message_media");
        A0v.append(" JOIN ");
        A0v.append("available_message_view AS message");
        C36321k7.A1O(" ON message_media.message_row_id = message._id", " LEFT JOIN ", "chat", " AS chat ON message.", A0v);
        C36321k7.A1O("chat_row_id", " = chat.", "_id", A1C, A0v);
        AnonymousClass000.A1D("message_type IN ('2', '1', '25', '3', '81', '28', '13', '29', '9', '26')", " AND (chat.chat_lock = 0", " OR chat.chat_lock is NULL)", A0v);
        A00 = A0v.toString();
        StringBuilder A0v2 = AnonymousClass000.A0v("SELECT ");
        C36321k7.A1O(AnonymousClass1M2.A01("message", strArr), ", ", "file_size", " FROM ", A0v2);
        C36321k7.A1O("message_media AS message_media", " JOIN ", "available_message_view AS message", " LEFT JOIN ", A0v2);
        C36321k7.A1O("chat", " AS chat ON message.", "chat_row_id", " = chat.", A0v2);
        A0v2.append("_id");
        A0v2.append(" WHERE message_media.message_row_id = message._id");
        C36321k7.A1O(" AND ", "message_type IN ('2', '1', '25', '3', '81', '28', '13', '29', '9', '26')", " AND (chat.chat_lock = 0", " OR chat.chat_lock is NULL)", A0v2);
        A01 = A0v2.toString();
        StringBuilder A0v3 = AnonymousClass000.A0v("SELECT ");
        String str = C56842wy.A01;
        A0v3.append(str);
        A0v3.append(", remove_files  FROM ");
        A0v3.append("deleted_messages_view");
        A0v3.append(A1C);
        AnonymousClass000.A1D("message_type in ('2' , '1' , '25' , '3' , '28' , '13' , '29' , '20' , '9' , '26' , '23' , '37' ) ", " AND ", "chat_row_id", A0v3);
        A03 = AnonymousClass000.A0q(" = ?", A0v3);
        StringBuilder A0u2 = AnonymousClass000.A0u();
        AnonymousClass000.A1D("SELECT ", str, " FROM ", A0u2);
        C36321k7.A1O("available_message_view", A1C, "message_type in ('2' , '1' , '25' , '3' , '28' , '13' , '29' , '20' , '9' , '26' , '23' , '37' ) ", " AND ", A0u2);
        A0u2.append("( NOT (message_type == 2 AND origin == 1)  OR (origin != 1))");
        A0u2.append(" AND ");
        A0u2.append("chat_row_id = ?");
        A09 = AnonymousClass000.A0q(" ORDER BY sort_id DESC", A0u2);
        StringBuilder A0I2 = C36321k7.A0I("SELECT ", str, " FROM ", "available_message_view", A1C);
        A0I2.append("+message_type in (2 , 1 , 25 , 3 , 28 , 13 , 29 , 20 , 9 , 26 , 23 , 37 ) ");
        A0I2.append(" AND ");
        A0I2.append("from_me = 0");
        A0I2.append(" AND ");
        A0I2.append("sort_id > ? ");
        A0I = AnonymousClass000.A0q(" ORDER BY sort_id ASC", A0I2);
        StringBuilder A0v4 = AnonymousClass000.A0v("SELECT ");
        C36321k7.A1O(AnonymousClass1M2.A01("message", strArr), " FROM ", "message_media AS message_media", " JOIN ", A0v4);
        A0v4.append("available_message_view AS message");
        A0v4.append(" ON message_media.message_row_id = message._id");
        A0v4.append(A1C);
        C36321k7.A1O("message_media.file_hash = ?", " AND ", "message_type in ('2' , '1' , '25' , '3' , '28' , '13' , '29' , '20' , '9' , '26' , '23' , '37' ) ", " ORDER BY sort_id DESC", A0v4);
        A07 = AnonymousClass000.A0q(" LIMIT 1000", A0v4);
        StringBuilder A0v5 = AnonymousClass000.A0v("SELECT ");
        C36321k7.A1O(AnonymousClass1M2.A01("message", strArr), " FROM ", "message_media AS message_media", " JOIN ", A0v5);
        C36321k7.A1O("available_message_view AS message", " WHERE message_media.message_row_id = message._id", " AND ", "message_media.file_hash = ?", A0v5);
        C36321k7.A1O(" AND ", "message_type in ('2' , '1' , '25' , '3' , '28' , '13' , '29' , '20' , '9' , '26' , '23' , '37' ) ", " ORDER BY sort_id DESC", " LIMIT 1000", A0v5);
        A08 = A0v5.toString();
        StringBuilder A0v6 = AnonymousClass000.A0v("SELECT ");
        C36321k7.A1O(AnonymousClass1M2.A01("message", strArr), " FROM ", "message_media AS message_media", " JOIN ", A0v6);
        C36321k7.A1O("available_message_view AS message", " ON message_media.message_row_id = message._id", A1C, "message_media.file_hash = ?", A0v6);
        A0v6.append(" AND ");
        AnonymousClass000.A1D("message.message_type = ?", " ORDER BY sort_id DESC", " LIMIT 1000", A0v6);
        A05 = A0v6.toString();
        StringBuilder A0v7 = AnonymousClass000.A0v("SELECT ");
        C36321k7.A1O(AnonymousClass1M2.A01("message", strArr), " FROM ", "message_media AS message_media", " JOIN ", A0v7);
        C36321k7.A1O("available_message_view AS message", " WHERE message_media.message_row_id = message._id", " AND ", "message_media.file_hash = ?", A0v7);
        C36321k7.A1O(" AND ", "message.message_type = ?", " ORDER BY sort_id DESC", " LIMIT 1000", A0v7);
        A06 = A0v7.toString();
        StringBuilder A0u3 = AnonymousClass000.A0u();
        A0u3.append("SELECT message_media.*, ");
        C36361kB.A1R("message", A0u3, new String[]{"timestamp"});
        A0u3.append(",");
        A00(A0u3, "message_type");
        C36321k7.A1O(AnonymousClass1M2.A01("message", new String[]{"media_url"}), " FROM ", "message_media AS message_media", " JOIN ", A0u3);
        A0u3.append("available_message_view AS message");
        A0u3.append(" ON message_media.message_row_id = message._id");
        A0u3.append(A1C);
        A0u3.append("file_hash = ?");
        A0u3.append(" AND ");
        A0u3.append("enc_file_hash IS NOT NULL");
        A0E = AnonymousClass000.A0q(" ORDER BY message_row_id DESC", A0u3);
        StringBuilder A0v8 = AnonymousClass000.A0v("SELECT message_media.*, ");
        A00(A0v8, "timestamp");
        A00(A0v8, "message_type");
        C36321k7.A1O(AnonymousClass1M2.A01("message", new String[]{"media_url"}), " FROM ", "message_media AS message_media", " JOIN ", A0v8);
        C36321k7.A1O("available_message_view AS message", " WHERE message_media.message_row_id = message._id", " AND ", "file_hash = ?", A0v8);
        A0v8.append(" AND ");
        A0F = AnonymousClass000.A0p("enc_file_hash IS NOT NULL", " ORDER BY message_row_id DESC", A0v8);
        StringBuilder A0v9 = AnonymousClass000.A0v("SELECT message_media.*, ");
        A00(A0v9, "timestamp");
        A00(A0v9, "message_type");
        C36321k7.A1O(AnonymousClass1M2.A01("message", new String[]{"media_url"}), " FROM ", "message_media AS message_media", " JOIN ", A0v9);
        C36321k7.A1O("available_message_view AS message", " ON message_media.message_row_id = message._id", A1C, "file_hash = ?", A0v9);
        A0v9.append(" AND ");
        C36321k7.A1O("enc_file_hash IS NOT NULL", " AND ", "message.message_type = ?", " ORDER BY sort_id DESC", A0v9);
        A0C = A0v9.toString();
        StringBuilder A0v10 = AnonymousClass000.A0v("SELECT message_media.*, ");
        A00(A0v10, "timestamp");
        A00(A0v10, "message_type");
        C36321k7.A1O(AnonymousClass1M2.A01("message", new String[]{"media_url"}), " FROM ", "message_media AS message_media", " JOIN ", A0v10);
        C36321k7.A1O("available_message_view AS message", " WHERE message_media.message_row_id = message._id", " AND ", "file_hash = ?", A0v10);
        A0v10.append(" AND ");
        C36321k7.A1O("enc_file_hash IS NOT NULL", " AND ", "message.message_type = ?", " ORDER BY sort_id DESC", A0v10);
        A0D = A0v10.toString();
        StringBuilder A0v11 = AnonymousClass000.A0v("SELECT message_media.*, ");
        String str2 = "chat_row_id";
        C36321k7.A1O(AnonymousClass1M2.A01("message", new String[]{str2, "from_me", "key_id"}), " FROM ", "message_media AS message_media", " JOIN ", A0v11);
        C36321k7.A1O("available_message_view AS message", " ON message_media.message_row_id = message._id", A1C, "file_hash = ?", A0v11);
        A0v11.append(" AND ");
        A0v11.append("enc_file_hash = ?");
        A0v11.append(" AND ");
        A0v11.append("message_type in ('3', '1' ) ");
        A0v11.append(" ORDER BY sort_id DESC");
        A0G = AnonymousClass000.A0q(" LIMIT 10", A0v11);
        StringBuilder A0v12 = AnonymousClass000.A0v("SELECT message_media.*, ");
        C36321k7.A1O(AnonymousClass1M2.A01("message", new String[]{str2, "from_me", "key_id"}), " FROM ", "message_media AS message_media", " JOIN ", A0v12);
        C36321k7.A1O("available_message_view AS message", " WHERE message_media.message_row_id = message._id", " AND ", "file_hash = ?", A0v12);
        A0v12.append(" AND ");
        C36321k7.A1O("enc_file_hash = ?", " AND ", "message_type in ('3', '1' ) ", " ORDER BY sort_id DESC", A0v12);
        A0H = AnonymousClass000.A0q(" LIMIT 10", A0v12);
        StringBuilder A0I3 = C36321k7.A0I("SELECT ", str, " FROM ", "available_message_view", A1C);
        A0I3.append("message_type  IN ('2', '1', '25', '3', '28', '13', '29')");
        A0I3.append(" AND ");
        AnonymousClass000.A1D(" ( NOT (message_type == 2 AND origin == 1)  OR (origin != 1))", " AND ", "chat_row_id = ?", A0I3);
        String obj = A0I3.toString();
        A0B = obj;
        StringBuilder A0v13 = AnonymousClass000.A0v("SELECT ");
        C36321k7.A1O(C56842wy.A00, " FROM ", "available_message_view", A1C, A0v13);
        A0v13.append("message_type  IN ('2', '1', '25', '3', '28', '13', '29')");
        A0v13.append(" AND ");
        AnonymousClass000.A1D(" ( NOT (message_type == 2 AND origin == 1)  OR (origin != 1))", " AND ", "chat_row_id = ?", A0v13);
        String obj2 = A0v13.toString();
        A0A = C36321k7.A0D(obj, " ORDER BY sort_id DESC");
        A04 = C36321k7.A0D(obj2, " ORDER BY sort_id DESC");
    }
}
