package X;

import android.content.Context;
import android.content.res.Resources;
import android.text.TextUtils;
import android.util.DisplayMetrics;
import android.util.TypedValue;
import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import com.whatsapp.R;
import com.whatsapp.TextEmojiLabel;
import com.whatsapp.WaFrameLayout;
import com.whatsapp.WaImageView;
import com.whatsapp.WaTextView;
import com.whatsapp.conversation.conversationrow.ConversationRowParticipantHeaderQuotedView;
import com.whatsapp.stickers.StickerView;

/* renamed from: X.3Lm  reason: invalid class name and case insensitive filesystem */
public abstract class C63803Lm {
    public static final WaFrameLayout A00(Context context) {
        Context context2 = context;
        Resources resources = context2.getResources();
        DisplayMetrics displayMetrics = resources.getDisplayMetrics();
        WaFrameLayout waFrameLayout = new WaFrameLayout(context2);
        waFrameLayout.setId(R.id.quoted_message_frame);
        C36381kD.A1A(waFrameLayout, -1, -2);
        waFrameLayout.setForeground(AnonymousClass00E.A00(context2, R.drawable.balloon_incoming_frame));
        LinearLayout linearLayout = new LinearLayout(context2);
        C36381kD.A1A(linearLayout, -1, -2);
        C36371kC.A13(context2, linearLayout, R.drawable.link_preview_background);
        linearLayout.setGravity(16);
        linearLayout.setMinimumHeight(C36431kI.A03(displayMetrics, (float) 48, 1));
        linearLayout.setMinimumWidth(C36431kI.A03(displayMetrics, (float) 120, 1));
        linearLayout.setOrientation(0);
        View view = new View(context2);
        view.setId(R.id.quoted_color);
        C36381kD.A1A(view, resources.getDimensionPixelSize(R.dimen.f7nameremoved), -1);
        linearLayout.addView(view);
        LinearLayout linearLayout2 = new LinearLayout(context2);
        LinearLayout.LayoutParams layoutParams = new LinearLayout.LayoutParams(0, -2);
        layoutParams.weight = 1.0f;
        linearLayout2.setLayoutParams(layoutParams);
        linearLayout2.setOrientation(1);
        float f = (float) 8;
        float f2 = f;
        float f3 = (float) 4;
        linearLayout2.setPadding(C36431kI.A03(displayMetrics, f, 1), C36431kI.A03(displayMetrics, f3, 1), C36431kI.A03(displayMetrics, f2, 1), C36431kI.A03(displayMetrics, f3, 1));
        ConversationRowParticipantHeaderQuotedView conversationRowParticipantHeaderQuotedView = new ConversationRowParticipantHeaderQuotedView(context2);
        conversationRowParticipantHeaderQuotedView.setId(R.id.quoted_title_frame);
        LinearLayout.LayoutParams layoutParams2 = new LinearLayout.LayoutParams(-2, -2);
        layoutParams2.gravity = 3;
        conversationRowParticipantHeaderQuotedView.setLayoutParams(layoutParams2);
        conversationRowParticipantHeaderQuotedView.setOrientation(0);
        TextEmojiLabel textEmojiLabel = new TextEmojiLabel(context2);
        A01(textEmojiLabel, R.id.quoted_title);
        C36331k8.A0r(context2, textEmojiLabel, R.color.f6nameremoved);
        conversationRowParticipantHeaderQuotedView.addView(textEmojiLabel);
        WaTextView waTextView = new WaTextView(context2);
        A01(waTextView, R.id.quoted_bullet_divider);
        waTextView.setPadding(C36431kI.A03(displayMetrics, f3, 1), 0, C36431kI.A03(displayMetrics, f3, 1), 0);
        waTextView.setText(R.string.f12nameremoved);
        C36331k8.A0r(context2, waTextView, R.color.f6nameremoved);
        waTextView.setVisibility(8);
        conversationRowParticipantHeaderQuotedView.addView(waTextView);
        TextEmojiLabel textEmojiLabel2 = new TextEmojiLabel(context2);
        A01(textEmojiLabel2, R.id.quoted_subtitle);
        textEmojiLabel2.setText(R.string.f12nameremoved);
        C36331k8.A0r(context2, textEmojiLabel2, R.color.f6nameremoved);
        textEmojiLabel2.setVisibility(8);
        conversationRowParticipantHeaderQuotedView.addView(textEmojiLabel2);
        linearLayout2.addView(conversationRowParticipantHeaderQuotedView);
        FrameLayout frameLayout = new FrameLayout(context2);
        frameLayout.setLayoutParams(new ViewGroup.MarginLayoutParams(-2, -2));
        TextEmojiLabel textEmojiLabel3 = new TextEmojiLabel(context2);
        textEmojiLabel3.setId(R.id.quoted_text);
        FrameLayout.LayoutParams layoutParams3 = new FrameLayout.LayoutParams(-2, -2);
        layoutParams3.gravity = 3;
        textEmojiLabel3.setLayoutParams(layoutParams3);
        textEmojiLabel3.setEllipsize(TextUtils.TruncateAt.END);
        C36331k8.A0r(context2, textEmojiLabel3, R.color.f6nameremoved);
        frameLayout.addView(textEmojiLabel3);
        StickerView stickerView = new StickerView(context2);
        stickerView.setId(R.id.quoted_sticker);
        FrameLayout.LayoutParams layoutParams4 = new FrameLayout.LayoutParams(resources.getDimensionPixelSize(R.dimen.f7nameremoved), resources.getDimensionPixelSize(R.dimen.f7nameremoved));
        float f4 = (float) 2;
        float f5 = f4;
        int A03 = C36431kI.A03(displayMetrics, f4, 1);
        layoutParams4.gravity = 3;
        int i = A03;
        layoutParams4.leftMargin = i;
        layoutParams4.rightMargin = i;
        layoutParams4.topMargin = i;
        layoutParams4.bottomMargin = i;
        stickerView.setLayoutParams(layoutParams4);
        stickerView.setVisibility(8);
        frameLayout.addView(stickerView);
        linearLayout2.addView(frameLayout);
        TextEmojiLabel textEmojiLabel4 = new TextEmojiLabel(context2);
        textEmojiLabel4.setId(R.id.quoted_sub_text);
        LinearLayout.LayoutParams layoutParams5 = new LinearLayout.LayoutParams(-2, -2);
        layoutParams5.gravity = 3;
        textEmojiLabel4.setLayoutParams(layoutParams5);
        textEmojiLabel4.setEllipsize(TextUtils.TruncateAt.END);
        textEmojiLabel4.setMaxLines(2);
        C36331k8.A0r(context2, textEmojiLabel4, R.color.f6nameremoved);
        textEmojiLabel4.setVisibility(8);
        linearLayout2.addView(textEmojiLabel4);
        linearLayout.addView(linearLayout2);
        WaImageView waImageView = new WaImageView(context2);
        waImageView.setId(R.id.quoted_thumb);
        float f6 = (float) 52;
        C36381kD.A1A(waImageView, C36431kI.A03(displayMetrics, f6, 1), -1);
        C36411kG.A1D(waImageView);
        linearLayout.addView(waImageView);
        WaImageView waImageView2 = new WaImageView(context2);
        waImageView2.setId(R.id.contact_photo);
        C36381kD.A1A(waImageView2, resources.getDimensionPixelSize(R.dimen.f7nameremoved), resources.getDimensionPixelSize(R.dimen.f7nameremoved));
        waImageView2.setScaleType(ImageView.ScaleType.FIT_CENTER);
        waImageView2.setVisibility(8);
        linearLayout.addView(waImageView2);
        FrameLayout frameLayout2 = new FrameLayout(context2);
        frameLayout2.setId(R.id.quoted_payment_amount_container);
        C36381kD.A1A(frameLayout2, -2, -1);
        frameLayout2.setVisibility(8);
        WaImageView waImageView3 = new WaImageView(context2);
        waImageView3.setId(R.id.quoted_payment_amount_expressive_background);
        C36381kD.A1A(waImageView3, C36431kI.A03(displayMetrics, f6, 1), -1);
        C36411kG.A1D(waImageView3);
        waImageView3.setVisibility(8);
        frameLayout2.addView(waImageView3);
        WaTextView waTextView2 = new WaTextView(context2);
        waTextView2.setId(R.id.quoted_payment_amount_text);
        FrameLayout.LayoutParams layoutParams6 = new FrameLayout.LayoutParams(-2, -1);
        layoutParams6.gravity = 17;
        waTextView2.setLayoutParams(layoutParams6);
        waTextView2.setMaxWidth(C36431kI.A03(displayMetrics, (float) 88, 1));
        float f7 = (float) 44;
        waTextView2.setMinWidth(C36431kI.A03(displayMetrics, f7, 1));
        waTextView2.setMinimumWidth(C36431kI.A03(displayMetrics, f7, 1));
        waTextView2.setBackgroundResource(R.drawable.payments_message_bubble_background);
        waTextView2.setGravity(17);
        float f8 = f2;
        waTextView2.setPadding(C36431kI.A03(displayMetrics, f8, 1), 0, C36431kI.A03(displayMetrics, f8, 1), 0);
        waTextView2.setMaxLines(1);
        AnonymousClass088.A03(waTextView2, 1);
        float f9 = (float) 12;
        AnonymousClass088.A07(waTextView2, C36431kI.A03(displayMetrics, f9, 2), C36431kI.A03(displayMetrics, (float) 20, 2), C36431kI.A03(displayMetrics, f5, 2), 0);
        C36331k8.A0r(context2, waTextView2, R.color.f6nameremoved);
        waTextView2.setTextSize(TypedValue.applyDimension(2, 14.0f, displayMetrics));
        frameLayout2.addView(waTextView2);
        linearLayout.addView(frameLayout2);
        waFrameLayout.addView(linearLayout);
        FrameLayout frameLayout3 = new FrameLayout(context2);
        frameLayout3.setId(R.id.cancel);
        FrameLayout.LayoutParams layoutParams7 = new FrameLayout.LayoutParams(-2, -2);
        layoutParams7.gravity = 53;
        frameLayout3.setLayoutParams(layoutParams7);
        C36331k8.A0q(context2, frameLayout3, R.string.f12nameremoved);
        float f10 = f5;
        frameLayout3.setPadding(C36431kI.A03(displayMetrics, f9, 1), C36431kI.A03(displayMetrics, f10, 1), C36431kI.A03(displayMetrics, f10, 1), C36431kI.A03(displayMetrics, f9, 1));
        frameLayout3.setVisibility(8);
        WaImageView waImageView4 = new WaImageView(context2);
        waImageView4.setId(R.id.cancel_image);
        float f11 = (float) 16;
        waImageView4.setLayoutParams(new ViewGroup.LayoutParams(C36431kI.A03(displayMetrics, f11, 1), C36431kI.A03(displayMetrics, f11, 1)));
        waImageView4.setBackgroundResource(R.drawable.semi_white_circle);
        waImageView4.setImageResource(R.drawable.ic_close);
        frameLayout3.addView(waImageView4);
        waFrameLayout.addView(frameLayout3);
        return waFrameLayout;
    }

    public static void A01(TextView textView, int i) {
        textView.setId(i);
        textView.setLayoutParams(new ViewGroup.MarginLayoutParams(-2, -2));
        textView.setEllipsize(TextUtils.TruncateAt.END);
        textView.setMaxLines(1);
        textView.setSingleLine();
    }
}
